/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime device info */
        get: operations["getSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/reboot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Soft-reboot the device
         * @description Replies 200 immediately, then calls `esp_restart()` after ~500ms.
         */
        post: operations["rebootSystem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current wall clock and NTP sync status */
        get: operations["getTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a CAN bus discovery pass
         * @description Scans the bus for unassigned modules. With `reset_assignments=true` the
         *     host first clears all short-ID assignments (modules will also reset their
         *     assignment state), then rediscovers — this is the "factory-fresh" path.
         *     Without it, new modules are merged into the existing registry.
         */
        post: operations["discover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/identify_pass": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show one flap on each target module for physical identification
         * @description Sends `display_flap` to a list of modules, one distinct flap each,
         *     so a technician can walk the wall and learn which UUID is at which
         *     physical position. Composable into multi-pass workflows when
         *     `modules.length` > `flaps.length` (frontend orchestrates).
         */
        post: operations["identifyPass"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full grid configuration */
        get: operations["getGrid"];
        /**
         * Replace the entire grid atomically
         * @description All-or-nothing. Rejects on any validation failure (unknown UUID format,
         *     out-of-bounds cell, duplicate cell, duplicate UUID) without mutating
         *     state. Does **not** verify each UUID is a known module — use `PUT
         *     /api/grid/cell` for interactive placement with existence checks.
         *     Does not auto-save; call `POST /api/grid/save` afterward.
         */
        put: operations["replaceGrid"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid/size": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set grid dimensions
         * @description Mappings at `x >= width` or `y >= height` are silently dropped.
         */
        post: operations["setGridSize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Place a module at a cell
         * @description Rejects if: cell out of bounds, cell already occupied, UUID already
         *     mapped elsewhere, or UUID not in the CAN device registry.
         */
        put: operations["putCell"];
        post?: never;
        /**
         * Clear a cell, or remove a module from wherever it is
         * @description Body must contain EITHER `uuid` OR `{x, y}`.
         */
        delete: operations["deleteCell"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid/cell/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atomically move a mapping to another cell
         * @description Destination must be empty.
         */
        post: operations["moveCell"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid/cell/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atomically swap two cells
         * @description Either or both cells may be empty.
         */
        post: operations["swapCell"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist the in-memory grid to NVS */
        post: operations["saveGrid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grid/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear all mappings and restore default dimensions
         * @description In-memory only. Call `POST /api/grid/save` to persist.
         */
        post: operations["resetGrid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all discovered modules */
        get: operations["listModules"];
        put?: never;
        /**
         * Bus-wide broadcast action
         * @description Dispatches to all modules. `display_all` respects quiet hours.
         */
        post: operations["broadcastAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cached status snapshot for all assigned modules
         * @description Zero CAN I/O — served from the background poller's cache. A full sweep
         *     completes approximately every 5 seconds. Each entry includes `stale_ms`
         *     so clients can detect dead data.
         */
        get: operations["modulesStatusAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["UuidPath"];
            };
            cookie?: never;
        };
        /**
         * Single module, fresh status + firmware info
         * @description Unlike `/api/modules/status`, this issues a fresh `get_status` and
         *     `get_device_info` over CAN (adds ~10-500 ms). Returns identity with
         *     `null` status/info if the UUID is not assigned.
         */
        get: operations["getModule"];
        put?: never;
        /**
         * Dispatch a command to a single module
         * @description `display_flap` and `queue_display_flap` respect quiet hours. All other
         *     actions are configuration and always go through.
         */
        post: operations["moduleAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The last frame that was actually sent
         * @description `flaps[y][x]` is the flap that was sent for that cell; cells with no
         *     mapped module are serialised as `-1`. If nothing has been sent since
         *     boot, `valid=false` and all other fields are `null`.
         */
        get: operations["getDisplay"];
        put?: never;
        /**
         * Enqueue a full-grid frame
         * @description Validates `flaps` dimensions match `Grid.width × Grid.height`. Values
         *     must be 0-63. Last-write-wins queue: if a frame is already pending,
         *     it is replaced. The worker task will fire `display.frame_sent` over
         *     WebSocket when the CAN send completes.
         */
        post: operations["postDisplay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/cell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update a single cell immediately (bypasses the queue)
         * @description Synchronous CAN `display_flap` — returns when the module ACKs or
         *     times out. Updates the last-frame snapshot on success.
         */
        post: operations["postDisplayCell"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fill every mapped cell with the blank flap (56) */
        post: operations["clearDisplay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get default effect, delay, and cycle_type */
        get: operations["getDisplaySettings"];
        put?: never;
        /**
         * Partial update of display settings
         * @description Any omitted field is unchanged. Changing `cycle_type` pushes
         *     `set_transition` to all known modules. Saves to NVS on success.
         */
        post: operations["updateDisplaySettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/display/effects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available stagger effects (9 built-in) */
        get: operations["listEffects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List saved presets (metadata only)
         * @description Does not include flaps arrays. Use `GET /api/presets/{id}` for the full record.
         */
        get: operations["listPresets"];
        put?: never;
        /** Create a preset */
        post: operations["createPreset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a preset (full record with flaps) */
        get: operations["getPreset"];
        /**
         * Replace a preset
         * @description Id must exist. Same body shape as `POST /api/presets`.
         */
        put: operations["updatePreset"];
        post?: never;
        /** Delete a preset */
        delete: operations["deletePreset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{id}/show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Display a preset
         * @description Rejects if preset dimensions don't match current grid.
         */
        post: operations["showPreset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all schedules */
        get: operations["listSchedules"];
        put?: never;
        /** Create a schedule */
        post: operations["createSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Get a schedule */
        get: operations["getSchedule"];
        /** Replace a schedule */
        put: operations["updateSchedule"];
        post?: never;
        /** Delete a schedule */
        delete: operations["deleteSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedules/{id}/run": {
        parameters: {
            query?: {
                /** @description Set `1` to bypass quiet hours. */
                force?: "0" | "1";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fire the schedule immediately
         * @description Updates `last_run_ms` on success. Respects quiet hours unless
         *     `?force=1` is set.
         */
        post: operations["runSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cross-cutting config */
        get: operations["getSettings"];
        put?: never;
        /**
         * Partial update of cross-cutting config
         * @description Omitted fields unchanged. Saves to NVS on success.
         */
        post: operations["updateSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiet_hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get quiet-hours windows and current-state flag */
        get: operations["getQuietHours"];
        /**
         * Replace the quiet-hours window list
         * @description Atomic full replacement (max 7 windows). Persists to NVS on success.
         */
        put: operations["replaceQuietHours"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Static 64-entry flap mapping
         * @description Fetch once and cache — never changes for a given firmware.
         */
        get: operations["getFlaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Device identity (model / type / firmware version)
         * @description Mirrors the mDNS `_device-info` service. `model` and `type` are
         *     set during boot via `kd_common_set_device_info()` — on this
         *     project that's `("cherry-blossom", "splitflap")`.
         */
        get: operations["getAbout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Network + NTP configuration
         * @description Runtime-mutable settings persisted to NVS by `kd_common`. Separate
         *     from `/api/settings` (which is this project's cross-cutting app
         *     settings).
         */
        get: operations["getSystemConfig"];
        put?: never;
        /**
         * Partial update of network + NTP config
         * @description Any omitted field is unchanged. Length caps:
         *     - `timezone`: < 64 chars
         *     - `ntp_server`: < 64 chars
         *     - `wifi_hostname`: 1–63 chars
         *     Request body is capped at 1024 bytes.
         */
        post: operations["updateSystemConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time/zonedb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full IANA timezone catalog
         * @description Streamed via HTTP/1.1 chunked transfer (20 zones per chunk). The
         *     response is a flat JSON array of `{name, rule}` entries, where
         *     `rule` is the POSIX TZ string suitable for `setenv("TZ", …)`.
         *     Use this to populate a timezone picker UI. ~400 entries, ~25 KB.
         */
        get: operations["getTimezoneDb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{wildcard}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Any sub-path under `/api/`. */
                wildcard: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        /**
         * CORS preflight (wildcard)
         * @description Built-in handler for all `OPTIONS /api/*` requests. Returns an
         *     empty body with the following CORS headers:
         *     - `Access-Control-Allow-Origin: *`
         *     - `Access-Control-Allow-Methods: GET,POST,PATCH,DELETE,OPTIONS`
         *     - `Access-Control-Allow-Headers: Content-Type,Authorization`
         *     - `Access-Control-Allow-Credentials: true`
         *
         *     Actual (non-preflight) responses also carry
         *     `Access-Control-Allow-Origin: *` via this project's pre-handler
         *     hook installed through `kd_common_api_set_pre_handler()`.
         */
        options: operations["corsPreflight"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket upgrade endpoint
         * @description Upgrade to WebSocket. Server pushes all clients a `welcome` message on
         *     connect, then broadcasts events as state changes. See the
         *     `WsEvent` schema (discriminated on `type`) for every possible
         *     server-to-client message.
         *
         *     **Client-to-server:** the only accepted message is `{"type":"ping"}`
         *     which is answered with `{"type":"pong","ts":<uptime_ms>}`. Any other
         *     payload is logged and ignored. Frames > 256 bytes from clients are
         *     dropped.
         */
        get: operations["websocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 12-character hex UUID (case-insensitive on input; uppercase on output).
         * @example AABBCCDDEEFF
         */
        Uuid: string;
        /** @description Transient 10-bit CAN short ID. May change across reboots. Readonly to clients. */
        ShortId: number;
        /** @description Index into the 64-entry flap mapping. */
        FlapIndex: number;
        /**
         * @description Per-module motion style. Mirrors CAN 0x0E Set Transition.
         *     `partial` = shortest path to target. `full` = always one full drum revolution.
         * @enum {string}
         */
        CycleType: "partial" | "full";
        /** @description Accepted in requests that take a transition mode; same semantics as CycleType. */
        TransitionModeInput: ("minimal" | "full_rotation") | (0 | 1);
        GridCoord: {
            x: number;
            y: number;
        };
        /**
         * @description 24-hour time of day, 'HH:MM'.
         * @example 22:00
         * @example 07:30
         */
        HhMm: string;
        /**
         * @description Bitmask of days-of-week this window applies to.
         *     Bit 0 = Sunday, bit 1 = Monday, …, bit 6 = Saturday (US calendar).
         */
        DayMask: number;
        OkResponse: {
            /** @constant */
            ok: true;
        };
        QuietHoursError: {
            /** @constant */
            error: "quiet_hours_active";
        };
        SystemInfo: {
            /** @description Build version from `esp_app_get_description`. */
            fw_version: string;
            fw_project: string;
            /** @description Build date stamp. */
            fw_built: string;
            idf_version: string;
            /** @description Device uptime in ms (`esp_timer_get_time()/1000`). */
            uptime_ms: number;
            free_heap: number;
            /** @description Lowest free-heap value seen since boot. */
            min_free_heap: number;
            /** @description STA MAC address, or null if unavailable. */
            mac?: string | null;
            /** @description Local IPv4 address, or null if not connected. */
            ip?: string | null;
            /** @description dBm, or null if not connected. */
            wifi_rssi?: number | null;
            wifi_ssid?: string | null;
            module_count: number;
            grid: {
                width: number;
                height: number;
                /** @description Count of occupied cells. */
                mapped: number;
            };
        };
        TimeInfo: {
            /**
             * @description Seconds-since-epoch × 1000. Treat as double since JSON can't hold u64 precisely.
             *     Before NTP sync, this is the Jan 1 1970 fallback clock.
             */
            unix_ms: number;
            /** @description ISO-8601 timestamp, or null if not yet synced. */
            iso: string | null;
            /** @description Day of week (0=Sun..6=Sat), or null if not yet synced. */
            dow: number | null;
            /** @description POSIX TZ string (set by kd_common via `TZ` env var). */
            timezone: string;
            /** @description true when `tm_year >= 120` (year ≥ 2020). */
            synced: boolean;
        };
        GridSize: {
            width: number;
            height: number;
        };
        GridMapping: {
            uuid: components["schemas"]["Uuid"];
            x: number;
            y: number;
        };
        Grid: {
            grid: components["schemas"]["GridSize"];
            mapping: components["schemas"]["GridMapping"][];
        };
        PutCellBody: {
            x: number;
            y: number;
            uuid: components["schemas"]["Uuid"];
        };
        /** @description Must contain EITHER `uuid` OR both `x` and `y`. If `uuid` is present it wins. */
        DeleteCellBody: {
            uuid: components["schemas"]["Uuid"];
        } | {
            x: number;
            y: number;
        };
        ModuleSummary: {
            uuid: components["schemas"]["Uuid"];
            short_id: components["schemas"]["ShortId"];
            /** @description 0x10 = Sakura split-flap module. */
            hw_type: number;
            assigned: boolean;
            /** @description At least one heartbeat received. */
            alive: boolean;
            /** @description Current grid position, or null if unmapped. */
            grid: components["schemas"]["GridCoord"] | null;
        };
        /**
         * @description Stepper state machine (mirrors CAN state enum):
         *     * idle — not moving
         *     * homing — initial home seek in progress
         *     * accel — accelerating toward target
         *     * cruise — at cruise speed
         *     * decel — decelerating toward target
         *     * rehoming — missed home sensor, recovery lap
         *     * error — stall or fault
         *     * unknown — unrecognized code
         * @enum {string}
         */
        StepperState: "idle" | "homing" | "accel" | "cruise" | "decel" | "rehoming" | "error" | "unknown";
        ModuleStatus: {
            homed: boolean;
            state: components["schemas"]["StepperState"];
            state_code: number;
            /** @description 0-63 or null if not homed (raw 0xFF from firmware). */
            flap: components["schemas"]["FlapIndex"] | null;
            /** @description Absolute motor step position. */
            step: number;
            /** @description Die temperature (°C). */
            temp_c: number;
        };
        ModuleStatusCached: {
            uuid: components["schemas"]["Uuid"];
            short_id: components["schemas"]["ShortId"];
            status: components["schemas"]["ModuleStatus"] | null;
            /** @description ms since the cache entry was last refreshed, or null if never. */
            stale_ms: number | null;
        };
        DeviceInfo: {
            /** @description Module firmware version "maj.min.patch". */
            fw: string;
            hw_type: number;
            /** @description Bitfield: bit0 assigned, bit1 homed, bit2 coils_on. */
            flags: number;
            /** @description Wraps at 65535. */
            uptime_min: number;
        };
        ModuleDetail: components["schemas"]["ModuleSummary"] & {
            /** @description Fresh poll result, or null if unassigned or CAN timeout. */
            status: components["schemas"]["ModuleStatus"] | null;
            /** @description Fresh firmware info, or null on error. */
            info: components["schemas"]["DeviceInfo"] | null;
        };
        /** @description POST body for `/api/modules/{uuid}`. Discriminated union on `action`. */
        ModuleActionRequest: components["schemas"]["ActionHome"] | components["schemas"]["ActionCalibrate"] | components["schemas"]["ActionDisplayFlap"] | components["schemas"]["ActionQueueDisplayFlap"] | components["schemas"]["ActionQueueStepTo"] | components["schemas"]["ActionSetQueueDelay"] | components["schemas"]["ActionIdentify"] | components["schemas"]["ActionSetSpeed"] | components["schemas"]["ActionSetAccel"] | components["schemas"]["ActionSetTransition"] | components["schemas"]["ActionSetStepsPerFlap"] | components["schemas"]["ActionReset"];
        ActionHome: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "home";
        };
        ActionCalibrate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "calibrate";
            /**
             * @description `step` selects a calibration phase.
             *     * `start` begins calibration (device must be homed & idle).
             *     * `step` jogs forward by `deci_steps` (unit = 0.1 motor-step).
             *     * `end` writes the accumulated offset to NVS.
             */
            param: {
                /** @enum {string} */
                step: "start" | "end";
            } | {
                /** @constant */
                step: "step";
                deci_steps: number;
            };
        };
        ActionDisplayFlap: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "display_flap";
            param: components["schemas"]["FlapIndex"];
        };
        ActionQueueDisplayFlap: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "queue_display_flap";
            param: components["schemas"]["FlapIndex"];
        };
        ActionQueueStepTo: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "queue_step_to";
            /** @description Absolute target motor step count. */
            param: number;
        };
        ActionSetQueueDelay: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_queue_delay";
            /** @description Delay (ms) between `run_queued` and move start. */
            param: number;
        };
        ActionIdentify: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "identify";
            /** @description Blink the module LED for N seconds (0 = cancel). */
            param: number;
        };
        ActionSetSpeed: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_speed";
            param: number;
        };
        ActionSetAccel: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_accel";
            /** @description steps/s² */
            param: number;
        };
        ActionSetTransition: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_transition";
            param: components["schemas"]["TransitionModeInput"];
        };
        ActionSetStepsPerFlap: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_steps_per_flap";
            /** @description Deci-steps per flap (0 = restore firmware default). */
            param: number;
        };
        ActionReset: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "reset";
        };
        ModuleActionResponse: {
            /** @constant */
            ok: true;
            action: string;
            short_id: components["schemas"]["ShortId"];
        } & {
            [key: string]: unknown;
        };
        /** @description POST body for `/api/modules`. Discriminated union on `action`. */
        BroadcastActionRequest: components["schemas"]["BcEmergencyStop"] | components["schemas"]["BcResetAll"] | components["schemas"]["BcRunQueued"] | components["schemas"]["BcHomeAll"] | components["schemas"]["BcDisplayAll"] | components["schemas"]["BcSetSpeedAll"] | components["schemas"]["BcSetTransitionAll"] | components["schemas"]["BcSetWaveDelay"] | components["schemas"]["BcSetAccelAll"] | components["schemas"]["BcSetStepsPerFlapAll"];
        BcEmergencyStop: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "emergency_stop";
        };
        BcResetAll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "reset_all";
        };
        BcRunQueued: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "run_queued";
        };
        BcHomeAll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "home_all";
        };
        BcDisplayAll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "display_all";
            param: components["schemas"]["FlapIndex"];
        };
        BcSetSpeedAll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_speed_all";
            param: number;
        };
        BcSetTransitionAll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_transition_all";
            param: components["schemas"]["TransitionModeInput"];
        };
        BcSetWaveDelay: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_wave_delay";
            /** @description ms per module index. */
            param: number;
        };
        BcSetAccelAll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_accel_all";
            param: number;
        };
        BcSetStepsPerFlapAll: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            action: "set_steps_per_flap_all";
            param: number;
        };
        BroadcastActionResponse: {
            /** @constant */
            ok: true;
            action: string;
        } & {
            [key: string]: unknown;
        };
        IdentifyPassRequest: {
            /** @description List of flap indices, one per target module. 1-64 entries. */
            flaps: components["schemas"]["FlapIndex"][];
            /**
             * @description Optional list of UUIDs to target. Must match `flaps.length` if provided.
             *     Omit to auto-target the first N assigned modules in registry order.
             */
            modules?: components["schemas"]["Uuid"][];
        };
        IdentifyPassAssignment: {
            uuid: components["schemas"]["Uuid"];
            short_id: components["schemas"]["ShortId"];
            flap: components["schemas"]["FlapIndex"];
            /** @description Whether the CAN send ACKed. */
            sent: boolean;
        };
        IdentifyPassResponse: {
            /** @constant */
            ok: true;
            count: number;
            sent_ok: number;
            pass: components["schemas"]["IdentifyPassAssignment"][];
        };
        LastFrame: {
            valid: boolean;
            width: number | null;
            height: number | null;
            /** @description Effect id used for the last send, or null. */
            effect: string | null;
            /** @description Delay (ms) used for the last send, or null. */
            delay: number | null;
            cycle_type: components["schemas"]["CycleType"] | null;
            /** @description Uptime ms (`esp_timer_get_time()/1000`) at send. Not a wall-clock epoch. */
            sent_at_ms: number | null;
            /**
             * @description 2-D row-major array. Cells where `Grid::uuid_at(x, y)` returns false
             *     are emitted as `-1`; otherwise 0-63.
             */
            flaps: (number | -1)[][] | null;
        };
        PostDisplayBody: {
            /** @description 2-D row-major array. Must match current `Grid.width × Grid.height`. */
            flaps: components["schemas"]["FlapIndex"][][];
            /** @description Override effect id for this send. Omit for default. */
            effect?: string;
            /** @description Override delay (ms) for this send. Omit for default. */
            delay?: number;
        };
        PostDisplayCellBody: {
            x: number;
            y: number;
            flap: components["schemas"]["FlapIndex"];
        };
        DisplaySettings: {
            /** @description Id from `/api/display/effects`. */
            effect: string;
            /** @description ms per wave step. */
            delay: number;
            cycle_type: components["schemas"]["CycleType"];
        };
        /** @description Any subset of DisplaySettings fields. Validated individually. */
        DisplaySettingsPatch: {
            effect?: string;
            delay?: number;
            cycle_type?: components["schemas"]["CycleType"];
        };
        EffectDef: {
            id: string;
            name: string;
            description: string;
        };
        PresetMeta: {
            id: number;
            name: string;
            width: number;
            height: number;
        };
        PresetFull: components["schemas"]["PresetMeta"] & {
            /** @description 2-D row-major, `width × height`, values 0-63. */
            flaps: components["schemas"]["FlapIndex"][][];
        };
        PresetBody: {
            name: string;
            flaps: components["schemas"]["FlapIndex"][][];
        };
        /** @description Discriminated union on `type`. */
        ScheduleAction: components["schemas"]["SchedActionDisplayPreset"] | components["schemas"]["SchedActionDisplaySolid"] | components["schemas"]["SchedActionClear"];
        SchedActionDisplayPreset: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "display_preset";
            preset_id: number;
        };
        SchedActionDisplaySolid: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "display_solid";
            flap: components["schemas"]["FlapIndex"];
        };
        SchedActionClear: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "clear";
        };
        Schedule: {
            id: number;
            name: string;
            /**
             * @description 5-field (standard) or 6-field (with seconds) cron string.
             *     Parsed server-side by `esp_cron`. 5-field input is auto-prepended
             *     with `0 ` for the seconds field.
             * @example 0 9 * * 1-5
             * @example *\/5 * * * *
             * @example 0 0 *\/2 * *
             * @example 0 0 9 * * 1-5
             */
            cron: string;
            enabled: boolean;
            obey_quiet_hours: boolean;
            action: components["schemas"]["ScheduleAction"];
            /** @description Wall-clock epoch ms of the last fire, or 0 if never. */
            last_run_ms: number;
        };
        ScheduleBody: {
            name: string;
            cron: string;
            /** @default true */
            enabled: boolean;
            /** @default true */
            obey_quiet_hours: boolean;
            action: components["schemas"]["ScheduleAction"];
        };
        Settings: {
            /** @description Free-form friendly name for this device. */
            device_name: string;
            /** @description Preset to show ~800 ms after boot discovery completes. 0 = none. */
            boot_preset_id: number;
            /** @description Pushed to all modules post-boot via `set_speed_all`. 0 = don't override. */
            default_speed: number;
            /** @description Pushed to all modules post-boot via `set_accel_all`. 0 = don't override. */
            default_accel: number;
            /** @description Periodic background discovery interval (seconds). 0 = disabled. */
            auto_discover_sec: number;
        };
        /** @description Any subset of Settings fields. */
        SettingsPatch: {
            device_name?: string;
            boot_preset_id?: number;
            default_speed?: number;
            default_accel?: number;
            auto_discover_sec?: number;
        };
        QuietWindow: {
            day_mask: components["schemas"]["DayMask"];
            start: components["schemas"]["HhMm"];
            /** @description If `end` < `start`, the window wraps midnight. */
            end: components["schemas"]["HhMm"];
            /** @default true */
            enabled: boolean;
        };
        QuietHours: {
            windows: components["schemas"]["QuietWindow"][];
            /**
             * @description Evaluated server-side against local-time + windows. Always `false`
             *     if time is not yet synced (safer default).
             */
            is_quiet_now: boolean;
        };
        /**
         * @description Each entry has `type` and `label`. The semantic rules:
         *       * type in {letter, digit, special}: `glyph` is a non-null string, `color` is null.
         *       * type == blank: `glyph` is `" "`, `color` is null.
         *       * type == color: `glyph` is null, `color` is a non-null `#RRGGBB` hex string.
         */
        FlapEntry: {
            id: components["schemas"]["FlapIndex"];
            /** @enum {string} */
            type: "letter" | "digit" | "special" | "blank" | "color";
            /** @description Canonical identifier, e.g. "char_A", "color_red". */
            label: string;
            /** @description Displayed UTF-8 character, or null for color blocks. */
            glyph: string | null;
            /** @description Hex color '#RRGGBB', or null for non-color entries. */
            color: string | null;
        };
        AboutInfo: {
            /**
             * @description Device model string set via `kd_common_set_device_info(model, …)`.
             *     Defaults to `"unknown"` if never set.
             */
            model: string;
            /** @description Device sub-type (second arg to `kd_common_set_device_info`). */
            type: string;
            /** @description Firmware version from `esp_app_get_description()`. */
            version: string;
        };
        SystemConfig: {
            /**
             * @description If true, kd_common uses a geolocation-derived timezone and the
             *     `timezone` field is informational. Set to false to use the
             *     `timezone` value as the source of truth.
             */
            auto_timezone: boolean;
            /**
             * @description POSIX TZ string (e.g. `EST5EDT,M3.2.0,M11.1.0`). Matches the
             *     `rule` field of an entry in `/api/time/zonedb`.
             */
            timezone: string;
            /** @description NTP server hostname (e.g. `pool.ntp.org`). */
            ntp_server: string;
            /** @description DHCP/mDNS hostname advertised by this device. */
            wifi_hostname: string;
        };
        /** @description Any subset of SystemConfig fields. */
        SystemConfigPatch: {
            auto_timezone?: boolean;
            timezone?: string;
            ntp_server?: string;
            wifi_hostname?: string;
        };
        TimezoneEntry: {
            /** @description Human-readable name (e.g. `America/New_York`). */
            name: string;
            /** @description POSIX TZ string suitable for `setenv("TZ", rule, 1)`. */
            rule: string;
        };
        WsEnvelopeBase: {
            type: string;
            /**
             * @description Sender's uptime in ms (`esp_timer_get_time()/1000`). Monotonic
             *     across a single boot; NOT a wall-clock timestamp. Use it for
             *     ordering within a session; for absolute time use `/api/time`.
             */
            ts: number;
        };
        /** @description All server-to-client frames on `/api/ws`. Discriminated on `type`. */
        WsEvent: components["schemas"]["WsEventWelcome"] | components["schemas"]["WsEventModuleDiscovered"] | components["schemas"]["WsEventModuleAlive"] | components["schemas"]["WsEventModuleDead"] | components["schemas"]["WsEventModuleStatus"] | components["schemas"]["WsEventDisplayFrameSent"] | components["schemas"]["WsEventDisplayCellSent"] | components["schemas"]["WsEventDisplaySettingsChanged"] | components["schemas"]["WsEventGridChanged"] | components["schemas"]["WsEventPresetAdded"] | components["schemas"]["WsEventPresetUpdated"] | components["schemas"]["WsEventPresetDeleted"] | components["schemas"]["WsEventDiscoveryStarted"] | components["schemas"]["WsEventDiscoveryComplete"] | components["schemas"]["WsEventScheduleFired"] | components["schemas"]["WsEventSettingsChanged"] | components["schemas"]["WsEventQuietHoursChanged"] | components["schemas"]["WsEventPong"];
        /**
         * @description Sent once to a client right after the WebSocket handshake completes.
         *     Gives the frontend a full initial snapshot so it doesn't need to
         *     follow up with several GETs.
         */
        WsEventWelcome: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "welcome";
            data: {
                system: components["schemas"]["SystemInfo"];
                settings: components["schemas"]["DisplaySettings"];
                grid: components["schemas"]["Grid"];
                modules: components["schemas"]["ModuleSummary"][];
                display: components["schemas"]["LastFrame"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "welcome";
        };
        WsEventModuleDiscovered: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "module.discovered";
            data: {
                uuid: components["schemas"]["Uuid"];
                short_id: components["schemas"]["ShortId"];
                hw_type: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "module.discovered";
        };
        WsEventModuleAlive: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "module.alive";
            data: {
                uuid: components["schemas"]["Uuid"];
                short_id: components["schemas"]["ShortId"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "module.alive";
        };
        WsEventModuleDead: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "module.dead";
            data: {
                uuid: components["schemas"]["Uuid"];
                short_id: components["schemas"]["ShortId"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "module.dead";
        };
        /**
         * @description Fires only when the poller observes a diff from the cached status (not
         *     every tick). With 6 idle modules at home, traffic settles to near-zero.
         */
        WsEventModuleStatus: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "module.status";
            data: {
                uuid: components["schemas"]["Uuid"];
                short_id: components["schemas"]["ShortId"];
                status: components["schemas"]["ModuleStatus"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "module.status";
        };
        WsEventDisplayFrameSent: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "display.frame_sent";
            data: components["schemas"]["LastFrame"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "display.frame_sent";
        };
        WsEventDisplayCellSent: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "display.cell_sent";
            data: {
                x: number;
                y: number;
                flap: components["schemas"]["FlapIndex"];
                uuid: components["schemas"]["Uuid"];
                short_id: components["schemas"]["ShortId"];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "display.cell_sent";
        };
        WsEventDisplaySettingsChanged: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "display.settings_changed";
            data: components["schemas"]["DisplaySettings"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "display.settings_changed";
        };
        WsEventGridChanged: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "grid.changed";
            data: components["schemas"]["Grid"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "grid.changed";
        };
        WsEventPresetAdded: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "preset.added";
            data: components["schemas"]["PresetMeta"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "preset.added";
        };
        WsEventPresetUpdated: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "preset.updated";
            data: components["schemas"]["PresetMeta"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "preset.updated";
        };
        WsEventPresetDeleted: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "preset.deleted";
            data: {
                id: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "preset.deleted";
        };
        WsEventDiscoveryStarted: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "discovery.started";
            data: {
                reset_assignments: boolean;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "discovery.started";
        };
        WsEventDiscoveryComplete: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "discovery.complete";
            data: {
                module_count: number;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "discovery.complete";
        };
        WsEventScheduleFired: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "schedule.fired";
            data: {
                id: number;
                /** @description Mirrors ScheduleAction.type. */
                action: string;
                blocked_by_quiet: boolean;
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "schedule.fired";
        };
        WsEventSettingsChanged: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "settings.changed";
            data: components["schemas"]["Settings"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "settings.changed";
        };
        WsEventQuietHoursChanged: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "quiet_hours.changed";
            data: {
                windows: components["schemas"]["QuietWindow"][];
            };
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "quiet_hours.changed";
        };
        WsEventPong: components["schemas"]["WsEnvelopeBase"] & {
            /** @constant */
            type: "pong";
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pong";
        };
        /**
         * @description Only `ping` is recognized. Server replies with `pong` envelope. Any
         *     other payload is logged and ignored (the connection is not dropped).
         */
        WsClientMessage: {
            /** @constant */
            type: "ping";
        };
    };
    responses: {
        /** @description Bad request — validation failure. Body is plain-text from `httpd_resp_send_err`. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Internal error (NVS, heap, etc). */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description CAN send or response timeout. */
        GatewayTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description Quiet hours are active; the action was blocked. */
        QuietHours: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["QuietHoursError"];
            };
        };
    };
    parameters: {
        UuidPath: components["schemas"]["Uuid"];
        IdPath: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    rebootSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reboot scheduled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        note: string;
                    };
                };
            };
        };
    };
    getTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Time info. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeInfo"];
                };
            };
        };
    };
    discover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    reset_assignments?: boolean;
                };
            };
        };
        responses: {
            /** @description Discovery complete. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        module_count: number;
                        reset_assignments: boolean;
                    };
                };
            };
        };
    };
    identifyPass: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentifyPassRequest"];
            };
        };
        responses: {
            /** @description Pass dispatched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentifyPassResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getGrid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grid snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
        };
    };
    replaceGrid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Grid"];
            };
        };
        responses: {
            /** @description New grid state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    setGridSize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GridSize"];
            };
        };
        responses: {
            /** @description Updated grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    putCell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutCellBody"];
            };
        };
        responses: {
            /** @description Updated grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    deleteCell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteCellBody"];
            };
        };
        responses: {
            /** @description Updated grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    moveCell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    from: components["schemas"]["GridCoord"];
                    to: components["schemas"]["GridCoord"];
                };
            };
        };
        responses: {
            /** @description Updated grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    swapCell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    a: components["schemas"]["GridCoord"];
                    b: components["schemas"]["GridCoord"];
                };
            };
        };
        responses: {
            /** @description Updated grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    saveGrid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    resetGrid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset grid snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
        };
    };
    listModules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module list with current assignment + grid position. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        modules: components["schemas"]["ModuleSummary"][];
                    };
                };
            };
        };
    };
    broadcastAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BroadcastActionRequest"];
            };
        };
        responses: {
            /** @description Broadcast dispatched. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BroadcastActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            423: components["responses"]["QuietHours"];
            500: components["responses"]["ServerError"];
        };
    };
    modulesStatusAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cached statuses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        modules: components["schemas"]["ModuleStatusCached"][];
                    };
                };
            };
        };
    };
    getModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["UuidPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    moduleAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["UuidPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleActionRequest"];
            };
        };
        responses: {
            /** @description Command result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleActionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            423: components["responses"]["QuietHours"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    getDisplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Last frame snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LastFrame"];
                };
            };
        };
    };
    postDisplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostDisplayBody"];
            };
        };
        responses: {
            /** @description Accepted and queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        queued: true;
                        note: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            423: components["responses"]["QuietHours"];
        };
    };
    postDisplayCell: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostDisplayCellBody"];
            };
        };
        responses: {
            /** @description Cell updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        x: number;
                        y: number;
                        flap: components["schemas"]["FlapIndex"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            423: components["responses"]["QuietHours"];
        };
    };
    clearDisplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blank frame queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        queued: true;
                        note: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            423: components["responses"]["QuietHours"];
        };
    };
    getDisplaySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Display settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplaySettings"];
                };
            };
        };
    };
    updateDisplaySettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplaySettingsPatch"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplaySettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["ServerError"];
        };
    };
    listEffects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effect catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        effects: components["schemas"]["EffectDef"][];
                    };
                };
            };
        };
    };
    listPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presets metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        presets: components["schemas"]["PresetMeta"][];
                        count: number;
                        /** @description Cap (32). */
                        max: number;
                    };
                };
            };
        };
    };
    createPreset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetBody"];
            };
        };
        responses: {
            /** @description New preset (full record). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetFull"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["ServerError"];
        };
    };
    getPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetFull"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetBody"];
            };
        };
        responses: {
            /** @description Updated preset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetFull"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        id: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    showPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        queued: true;
                        id: number;
                        name: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            423: components["responses"]["QuietHours"];
        };
    };
    listSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        schedules: components["schemas"]["Schedule"][];
                        count: number;
                        /** @description Cap (32). */
                        max: number;
                    };
                };
            };
        };
    };
    createSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleBody"];
            };
        };
        responses: {
            /** @description New schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleBody"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                        id: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    runSchedule: {
        parameters: {
            query?: {
                /** @description Set `1` to bypass quiet hours. */
                force?: "0" | "1";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fired. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            404: components["responses"]["NotFound"];
            423: components["responses"]["QuietHours"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["ServerError"];
        };
    };
    getQuietHours: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quiet-hours list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuietHours"];
                };
            };
        };
    };
    replaceQuietHours: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    windows: components["schemas"]["QuietWindow"][];
                };
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuietHours"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getFlaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flap catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        flaps: components["schemas"]["FlapEntry"][];
                        /** @constant */
                        count: 64;
                    };
                };
            };
        };
    };
    getAbout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AboutInfo"];
                };
            };
        };
    };
    getSystemConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current config. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConfig"];
                };
            };
        };
    };
    updateSystemConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemConfigPatch"];
            };
        };
        responses: {
            /** @description Updated (minimal success envelope). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "success";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Socket receive timeout. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getTimezoneDb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Timezone list. */
            200: {
                headers: {
                    "Transfer-Encoding"?: "chunked";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimezoneEntry"][];
                };
            };
        };
    };
    corsPreflight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Any sub-path under `/api/`. */
                wildcard: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preflight ACK. */
            200: {
                headers: {
                    "Access-Control-Allow-Origin"?: string;
                    "Access-Control-Allow-Methods"?: string;
                    "Access-Control-Allow-Headers"?: string;
                    "Access-Control-Allow-Credentials"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    websocket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols (WebSocket upgrade). */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
